name: ferdi-ci-cd

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "client/**"
      - ".github/workflows/ci-cd.yml"
  pull_request:
    branches: [ main ]   # <— no paths filter so every PR runs

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  ACR_REPO: ironhack.final.project

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: auth
            context: backend/auth
          - name: discounts
            context: backend/discounts
          - name: items
            context: backend/items
          - name: client
            context: client
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: |
          az acr login -n "$ACR_NAME"

      - name: Compute image tag
        id: tag
        run: |
          sha="${{ github.sha }}"
          echo "tag=v0.1.0-${sha::7}" >> $GITHUB_OUTPUT

      - name: Build & push ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.context }}/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPO }}:${{ matrix.service.name }}-${{ steps.tag.outputs.tag }}
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_REPO }}:${{ matrix.service.name }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to AKS
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get AKS creds
        run: az aks get-credentials -g rg-ferdi-aks-uksouth -n aks-ferdi-uksouth --overwrite-existing
      - name: Rollout status
        run: |
          kubectl -n ferdi rollout status deploy/auth-deploy
          kubectl -n ferdi rollout status deploy/discounts-deploy
          kubectl -n ferdi rollout status deploy/items-deploy
          kubectl -n ferdi rollout status deploy/client-deploy

